name: ğŸ— _Deploy Heroku

on:
  workflow_call:
    inputs:
      heroku-app-name:
        required: true
        type: string

jobs:
  heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ inputs.heroku-app-name }} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
