<<<<<<< HEAD
# This workflow will run whenever a PR is opened or changed.
#
# It will run tests and a few safety checks.
#
# If everything passes it can be set to auto-deploy to your staging app on Heroku.
#
# This workflow is primarily meant to be triggered automatically, but it can be run manually.
name: " ðŸš… _ BT - Internal CI Pipeline"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ "main" ]

jobs:
  super_scaffolding:
    name: ðŸ—ï¸ Super Scaffolding Tests
    uses: ./.github/workflows/_run_super_scaffolding_tests.yml
    secrets: inherit
||||||| 3ff18b8
=======
# This workflow will run whenever a PR is opened or changed.
#
# It will run tests and a few safety checks.
#
# If everything passes it can be set to auto-deploy to your staging app on Heroku.
#
# This workflow is primarily meant to be triggered automatically, but it can be run manually.
name: " ðŸš… _ BT - Internal CI"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ "main" ]

jobs:
  super_scaffolding:
    # This makes it so that this job only runs in the starter repo itself, and not in
    # applications started from the starter repo. If you want to run super scaffolding
    # test for your own app you can remove or comment out this next line.
    if: github.repository == 'bullet-train-co/bullet_train'
    name: ðŸ—ï¸ Super Scaffolding Tests
    uses: ./.github/workflows/_run_super_scaffolding_tests.yml
    secrets: inherit
>>>>>>> v1.6.18
